import { mkdir, writeFile } from 'node:fs/promises';
import { areas, reviews, IG, FB, MAPS } from '../src/content.js';
const siteBase=process.env.SITE_BASE||'/';
const live=siteBase!=='/';
const siteOrigin='https://fog-coder.github.io';

const arrow = '<span aria-hidden="true">↗&#xfe0e;</span>';
const button = (text, href, cls='') => `<a class="button ${cls}" href="${href}"><span>${text}</span><i aria-hidden="true">↗&#xfe0e;</i></a>`;
const link = (text,href) => `<a class="text-link" href="${href}">${text}${arrow}</a>`;
const photo = (name,alt,cls='',eager=false) => {
 const [width,height]=name==='fiore'?[1440,960]:name==='gabriela'?[1024,1024]:[1086,1448];
 const avif=eager&&name==='fiore';
 return `${avif?'<picture><source srcset="/media/fiore.avif" type="image/avif">':''}<img class="${cls}" src="/media/${name}.webp" srcset="/media/${name}-640.webp 640w, /media/${name}.webp ${width}w" sizes="(max-width: 767px) 100vw, 60vw" alt="${alt}" width="${width}" height="${height}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">${avif?'</picture>':''}`;
};
const logo = `<img src="/media/logo.webp" width="102" height="94" alt="Beauty Obsession, centro estetico" class="logo">`;
const routes=[['/','Home'],['/il-centro/','Il centro'],['/trattamenti/','Trattamenti'],['/contatti/','Contatti']];

function header(page){return `<a class="skip-link" href="#contenuto">Vai al contenuto</a><header class="site-header"><a class="brand" href="/" aria-label="Beauty Obsession, home">${logo}</a><nav class="desktop-nav" aria-label="Navigazione principale">${routes.slice(1).map(([href,title])=>`<a href="${href}" ${page===href?'aria-current="page"':''}>${title}</a>`).join('')}</nav><a class="header-book" href="/contatti/#richiesta">Un momento per te ${arrow}</a><button class="menu-toggle" type="button" aria-label="Apri menu" aria-expanded="false" aria-controls="menu-dialog"><span></span><span></span></button></header><dialog id="menu-dialog" class="menu-dialog" aria-label="Menu principale"><button class="menu-close" aria-label="Chiudi menu">Chiudi <span aria-hidden="true">×</span></button><div class="menu-inner"><p class="eyebrow">Beauty Obsession</p><nav aria-label="Menu mobile">${routes.map(([href,title],i)=>`<a href="${href}" ${page===href?'aria-current="page"':''}><small>0${i+1}</small>${title}${arrow}</a>`).join('')}</nav><div class="menu-bottom"><p>Via San Martino 10<br>Boffalora d’Adda, Lodi</p>${link('Instagram',IG)}</div></div></dialog>`;}

function footer(){return `<footer class="footer"><div class="footer-top"><a href="/" aria-label="Beauty Obsession, home">${logo}</a><p>La cura che ti somiglia.<br>Il tempo che ti appartiene.</p><div class="footer-social">${link('Instagram',IG)}${link('Facebook',FB)}</div></div><div class="footer-word" aria-hidden="true">Beauty <em>Obsession</em></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Beauty Obsession</span><a href="${MAPS}" target="_blank" rel="noopener noreferrer">Via San Martino 10 · Boffalora d’Adda (LO)</a><button type="button" class="privacy-open">Privacy</button><a href="#top" class="back-top">Torna su ↑</a></div></footer><dialog class="privacy-dialog" aria-labelledby="privacy-title"><button class="privacy-close" aria-label="Chiudi informativa">×</button><h2 id="privacy-title">La tua privacy.</h2><p>Questo sito non utilizza strumenti di analisi, cookie pubblicitari o contenuti social incorporati.</p><p>Il messaggio per l’appuntamento viene composto soltanto nel tuo browser. Non viene salvato o inviato dal sito. Puoi copiarlo e scegliere di inviarlo attraverso Instagram.</p><p>I collegamenti a Instagram, Facebook e Google Maps aprono servizi esterni, ai quali si applicano le rispettive informative.</p></dialog>`;}

function invitation(){return `<section class="invitation section-pad"><div class="invitation-art" aria-hidden="true">${photo('fiore','')}</div><div class="invitation-content"><p class="eyebrow">Ci prendiamo cura di te</p><h2 data-reveal>Il prossimo momento<br>è <em>il tuo.</em></h2>${button('Prendiamoci un appuntamento','/contatti/#richiesta')}</div></section>`;}

function testimonial(){return `<section class="testimonials section-pad" aria-labelledby="review-heading"><div class="review-heading"><h2 id="review-heading" class="eyebrow">Le parole di chi ci sceglie</h2><a class="review-score" href="${MAPS}" target="_blank" rel="noopener noreferrer"><strong>5,0</strong><span><span class="stars" aria-label="5 stelle su 5">★★★★★</span><small>88 recensioni su Google</small></span></a></div><div class="review-stage" aria-live="polite">${reviews.map((r,i)=>`<figure class="review" ${i?'hidden':''} data-review="${i}"><blockquote>“${r.quote}”</blockquote><figcaption>${r.name}<span>Recensione Google · ${r.stars}/5</span></figcaption></figure>`).join('')}</div><div class="review-bottom"><a class="text-link" href="${MAPS}" target="_blank" rel="noopener noreferrer">Leggi su Google ${arrow}</a><div class="review-controls"><button data-review-prev aria-label="Recensione precedente">←</button><span data-review-count aria-hidden="true">01 / 03</span><button data-review-next aria-label="Recensione successiva">→</button></div></div></section>`;}

const home = `<section class="hero" aria-labelledby="hero-title"><div class="hero-stage"><div class="hero-art" aria-hidden="true">${photo('fiore','','hero-poster',true)}<div class="hero-destination">${photo('pelle','')}</div><canvas id="bloom-canvas"></canvas></div><div class="hero-wash"></div><div class="hero-content"><p class="eyebrow">Centro estetico · Boffalora d’Adda</p><h1 id="hero-title"><span>Il tempo di</span> <em>rifiorire.</em></h1><div class="hero-bottom"><p>La bellezza di sentirsi bene.<br>Un gesto di cura, tutto tuo.</p>${button('Scopri i trattamenti','/trattamenti/')}</div></div><div class="hero-interlude" aria-hidden="true">Rallenta.</div><div class="hero-chapter" aria-hidden="true"><p class="eyebrow">Ritrova il tuo equilibrio</p><h2>La tua luce.<br><em>Naturalmente.</em></h2><p>Viso, corpo, mani e piedi.<br>Attenzioni che partono da te.</p><a class="text-link" href="#rituali" tabindex="-1">Esplora i rituali ${arrow}</a></div><div class="hero-foot"><span>Estetica. Benessere. Ascolto.</span><a href="#rituali" class="hero-skip">I nostri rituali <span aria-hidden="true">↓</span></a></div><button class="motion-toggle" aria-pressed="false" aria-label="Pausa movimento">Pausa movimento <span aria-hidden="true">Ⅱ</span></button></div></section>
<section class="manifesto section-pad"><p class="eyebrow">Beauty Obsession</p><h2 class="word-reveal">La bellezza è un modo<br>di sentirsi. <em>Il tuo.</em></h2><div class="manifesto-bottom"><span class="tiny-line"></span><p>Nel nostro centro a Boffalora d’Adda, ogni trattamento parte dall’ascolto. Perché prendersi cura di te significa prima di tutto conoscerti.</p>${link('Entra nel nostro mondo','/il-centro/')}</div></section>
<section class="rituals section-pad" id="rituali"><div class="section-intro"><p class="eyebrow">I nostri trattamenti</p><h2 data-reveal>La cura prende<br><em>la tua forma.</em></h2></div><div class="ritual-layout"><div class="ritual-image">${areas.map((a,i)=>photo(a.image,a.alt,`ritual-photo ${i===0?'active':''}`)).join('')}<div class="image-index" aria-hidden="true"><span data-ritual-number>01</span><span>/ 04</span></div></div><div class="ritual-list">${areas.map((a,i)=>`<a class="ritual-row ${i===0?'active':''}" href="/trattamenti/#${a.id}" data-ritual="${i}"><span class="ritual-num">0${i+1}</span><div><h3>${a.name}</h3><p>${a.short}</p></div>${arrow}</a>`).join('')}${link('Tutti i trattamenti','/trattamenti/')}</div></div></section>
<section class="foot-feature section-pad"><div class="foot-copy"><p class="eyebrow">La nostra specializzazione</p><h2 data-reveal>Il benessere<br>parte dai<br><em>tuoi passi.</em></h2><p>Pedicure estetica e curativa, precisione e delicatezza. Un’attenzione speciale ai piedi, per prenderti cura di te fin dai più piccoli dettagli.</p>${link('Scopri la cura dei piedi','/trattamenti/#piedi')}<span class="signature-detail">Passione, fino in fondo.</span></div><div class="foot-image media-reveal">${photo('piedi','Immagine editoriale della cura dei piedi, su lino avorio')}</div></section>
<section class="human-section section-pad"><div class="portrait-wrap media-reveal">${photo('gabriela','Ritratto pubblicato dal profilo ufficiale di Beauty Obsession')}<span class="portrait-caption">Un sorriso, prima di tutto.</span></div><div class="human-copy"><p class="eyebrow">Il cuore di Beauty Obsession</p><h2 data-reveal>La cura ha<br><em>un nome.</em></h2><p class="human-name">Gabriela.</p><p>Ascolto, precisione e passione per l’estetica. Dietro ogni gesto c’è il desiderio di farti sentire accolta, consigliata e a tuo agio.</p>${link('Conosci il centro','/il-centro/')}</div></section>${testimonial()}${invitation()}`;

const treatments = `<section class="page-hero treatments-hero"><div><p class="eyebrow">I trattamenti</p><h1>Ogni dettaglio,<br><em>parla di te.</em></h1><p>Dalla cura dei piedi alla luce del viso.<br>Trova il tuo momento di benessere.</p></div><div class="page-hero-art">${photo('pelle','Ritratto editoriale dedicato alla cura della pelle','',true)}</div></section><nav class="area-nav" aria-label="Aree dei trattamenti">${areas.map(a=>`<a href="#${a.id}">${a.name}</a>`).join('')}</nav><div class="treatment-catalogue">${areas.map((a,i)=>`<section class="treatment-area section-pad" id="${a.id}" aria-labelledby="heading-${a.id}"><div class="treatment-visual"><div class="treatment-photo media-reveal">${photo(a.image,a.alt)}</div><span class="area-number" aria-hidden="true">0${i+1}</span></div><div class="treatment-copy"><p class="eyebrow">${a.short}</p><h2 id="heading-${a.id}" data-reveal>${a.name.replace(' & ','<br><em>& ')+(a.name.includes('&')?'</em>':'')}</h2><p class="area-intro">${a.intro}</p><div class="service-accordions">${a.services.map((s,j)=>`<details ${j===0?'open':''}><summary>${s.name}<span aria-hidden="true">+</span></summary><div class="details-body"><p>${s.text}</p>${s.note?`<small>${s.note}</small>`:''}<a class="text-link" href="/contatti/?trattamento=${encodeURIComponent(s.name)}#richiesta">Parliamone insieme ${arrow}</a></div></details>`).join('')}</div></div></section>`).join('')}</div><section class="faq section-pad"><div><p class="eyebrow">Prima del tuo appuntamento</p><h2 data-reveal>Una domanda?<br><em>Ti ascoltiamo.</em></h2></div><div class="faq-list"><details><summary>Come scelgo il trattamento?<span aria-hidden="true">+</span></summary><p>Raccontaci le tue esigenze. Ti aiuteremo a conoscere i servizi disponibili e a scegliere il tuo appuntamento.</p></details><details><summary>Come posso prenotare?<span aria-hidden="true">+</span></summary><p>Puoi contattarci sul profilo Instagram ufficiale. Concordiamo insieme servizio, giorno e orario. La prenotazione è confermata dopo la risposta del centro.</p></details><details><summary>Dove trovo prezzi e durata?<span aria-hidden="true">+</span></summary><p>Scrivici indicando il trattamento che ti interessa: ti daremo le informazioni sul servizio, sulla durata e sul costo prima di fissare l’appuntamento.</p></details><details><summary>Il centro è accessibile?<span aria-hidden="true">+</span></summary><p>La scheda Google del centro segnala ingresso, bagno e parcheggio accessibili in sedia a rotelle. Per esigenze specifiche, contattaci prima della visita.</p></details></div></section>${invitation()}`;

const centre = `<section class="page-hero centre-hero"><div><p class="eyebrow">Il centro</p><h1>La bellezza<br>dell’<em>ascolto.</em></h1><p>Prima del trattamento, una persona.<br>Prima di tutto, tu.</p></div><div class="centre-hero-portrait">${photo('gabriela','Ritratto ufficiale di Beauty Obsession','',true)}<span class="portrait-caption">Il cuore di Beauty Obsession</span></div></section><section class="centre-story section-pad"><div class="story-title"><p class="eyebrow">Piacere, Gabriela</p><h2 data-reveal>Una passione.<br>Mille <em>attenzioni.</em></h2></div><div class="story-text"><p class="lead">Beauty Obsession è un luogo in cui il tempo torna ad essere tuo.</p><p>A Boffalora d’Adda, Gabriela si dedica all’estetica con precisione e passione. Le clienti raccontano un ambiente accogliente, la cura dei dettagli e il piacere di sentirsi ascoltate.</p><p>La cura professionale dei piedi occupa un posto speciale nel suo percorso. Alla pratica si affianca la formazione dichiarata nel metodo RUCK e nel percorso Podo Specialist.</p><p>Da mani e piedi al viso, dai massaggi all’epilazione: il punto di partenza è sempre conoscere le tue esigenze.</p><span class="written-signature">Ti aspetto, Gabriela</span></div></section><section class="values section-pad"><h2 class="word-reveal">Farti stare bene.<br>È qui che mettiamo<br><em>tutta la nostra cura.</em></h2><div class="values-grid"><article><span>01</span><h3>Ascolto</h3><p>Uno spazio per raccontarci ciò che desideri e ciò di cui hai bisogno.</p></article><article><span>02</span><h3>Attenzione</h3><p>La precisione dei gesti e la delicatezza che ogni persona merita.</p></article><article><span>03</span><h3>Passione</h3><p>La curiosità di continuare a formarsi e prendersi cura di ogni dettaglio.</p></article></div></section>${testimonial()}${invitation()}`;

const contact = `<section class="contact-hero section-pad"><p class="eyebrow">Vieni a trovarci</p><h1>Il tuo tempo.<br><em>Ti aspettiamo.</em></h1><div class="contact-lead"><p>A Boffalora d’Adda,<br>un piccolo spazio per stare bene.</p>${link('Apri le indicazioni',MAPS)}</div></section><section class="contact-grid section-pad"><div class="address"><p class="eyebrow">Dove siamo</p><h2>Ci vediamo<br>in <em>San Martino.</em></h2><address>Via San Martino 10<br>26811 Boffalora d’Adda (LO)</address>${button('Come raggiungerci',MAPS,'button-light')}<p class="accessibility-note">Ingresso, bagno e parcheggio accessibili in sedia a rotelle, come indicato nella scheda Google del centro.</p></div><div class="hours"><p class="eyebrow">Il tempo per te</p><h2>I nostri <em>orari.</em></h2><dl><div><dt>Martedì · Mercoledì · Giovedì</dt><dd>09:30 – 19:30</dd></div><div><dt>Venerdì · Sabato</dt><dd>09:30 – 17:30</dd></div><div><dt>Domenica · Lunedì</dt><dd>Chiuso</dd></div></dl><p>La prenotazione è consigliata.<br>Per festività e variazioni, scrivici prima di passare.</p></div></section><section class="booking section-pad" id="richiesta"><div class="booking-heading"><p class="eyebrow">Cominciamo da un messaggio</p><h2 data-reveal>Raccontaci<br>il tuo <em>desiderio.</em></h2><p>Scegli un trattamento e prepara il tuo messaggio. Poi scrivici su Instagram: concorderemo insieme il tuo appuntamento.</p>${link('Preferisci Facebook?',FB)}</div><form class="booking-form"><label for="treatment">Di cosa vorresti prenderti cura?</label><select id="treatment" name="trattamento"><option value="">Vorrei un consiglio</option>${areas.map(a=>`<optgroup label="${a.name}">${a.services.map(s=>`<option>${s.name}</option>`).join('')}</optgroup>`).join('')}</select><label for="availability">Quando vorresti venire? <span>(facoltativo)</span></label><input id="availability" name="disponibilita" type="text" maxlength="180" placeholder="Ad esempio, martedì nel pomeriggio" autocomplete="off"><label for="message">Il tuo messaggio</label><textarea id="message" name="messaggio" rows="4" maxlength="1000">Ciao Beauty Obsession! Vorrei un consiglio per scegliere un trattamento e fissare un appuntamento. Grazie!</textarea><div class="booking-actions"><button class="button button-light" type="submit"><span>Copia il messaggio</span><i aria-hidden="true">＋</i></button><a class="button" href="${IG}" target="_blank" rel="noopener noreferrer"><span>Apri Instagram</span><i aria-hidden="true">↗&#xfe0e;</i></a></div><p class="form-status" role="status" aria-live="polite"></p><p class="form-note">Incolla il messaggio nella chat del profilo ufficiale. L’appuntamento sarà confermato direttamente dal centro.</p></form></section><section class="social-strip section-pad"><p>Un po’ di Beauty Obsession,<br><em>anche tra un appuntamento e l’altro.</em></p>${button('Seguici su Instagram',IG,'button-light')}</section>`;

const pages=[
 {path:'',key:'home',title:'Beauty Obsession | Il tempo di rifiorire',description:'Centro estetico a Boffalora d’Adda. Cura dei piedi, trattamenti viso e corpo, epilazione e attenzioni dedicate al tuo benessere.',body:home},
 {path:'trattamenti',key:'trattamenti',title:'Trattamenti | Beauty Obsession, Boffalora d’Adda',description:'Pedicure, manicure, viso, massaggi, pressoterapia ed epilazione. Scopri i trattamenti di Beauty Obsession e richiedi il tuo appuntamento.',body:treatments},
 {path:'il-centro',key:'centro',title:'Il centro e Gabriela | Beauty Obsession',description:'Ascolto, precisione e passione. Conosci Beauty Obsession e Gabriela, centro estetico a Boffalora d’Adda.',body:centre},
 {path:'contatti',key:'contatti',title:'Contatti e appuntamenti | Beauty Obsession',description:'Beauty Obsession, via San Martino 10 a Boffalora d’Adda. Orari, indicazioni e canali ufficiali per richiedere un appuntamento.',body:contact}
];
for(const p of pages){
 const pagePath=p.path?`/${p.path}/`:'/';
 const canonical=siteOrigin+siteBase+p.path+(p.path?'/':'');
 let html=`<!doctype html><html lang="it"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#F7EEE8">${live?`<link rel="canonical" href="${canonical}"><meta property="og:url" content="${canonical}">`:'<meta name="robots" content="noindex,nofollow">'}<title>${p.title}</title><meta name="description" content="${p.description}"><meta property="og:title" content="${p.title}"><meta property="og:description" content="${p.description}"><meta property="og:type" content="website"><meta property="og:locale" content="it_IT"><meta property="og:image" content="${live?siteOrigin+siteBase:'/'}media/fiore.webp"><link rel="icon" href="/media/logo.webp" type="image/webp"><link rel="stylesheet" href="/src/style.css"><script type="module" src="/src/main.js"></script></head><body id="top" data-page="${p.key}">${header(pagePath)}<main id="contenuto">${p.body}</main>${footer()}<div class="page-curtain" aria-hidden="true"></div></body></html>`;
 if(live)html=html.replace(/\b(href|src|content)="\/(?!\/|src\/)/g,`$1="${siteBase}`).replace(/\bsrcset="([^"]+)"/g,(_,value)=>`srcset="${value.replace(/(^|,\s*)\//g,`$1${siteBase}`)}"`);
 await mkdir(p.path||'.',{recursive:true});await writeFile(`${p.path?p.path+'/':''}index.html`,html);
}
console.log(`Generated ${pages.length} static pages.`);
